#Project GUI-based Tic Tac Toe Game

#Importing Libraries
from tkinter import *
from tkinter import ttk
from tkinter import messagebox
from PIL import ImageTk, Image
import pyttsx3

#Creating GUI Window
root = Tk()
root.title("Tic Tac Toe Game")
root.geometry("500x500")
root.configure(background="black")
root.resizable(False, False)
icon = ImageTk.PhotoImage(Image.open("ttt_img.png"))
root.iconphoto(False, icon)

#Speech Synthesis Initialization and Statement
synthesizer = pyttsx3.init()
synthesizer.say("Game Starts!")
synthesizer.runAndWait()
synthesizer.stop()

#GUI Widgets Loading
img = ImageTk.PhotoImage(Image.open("img.webp"))
label_image = Label(root, image=img)
label_image.place(relx=0.5, rely=0.5, anchor=CENTER)

XO_turn = Label(root, text="It is the turn of X", bg="green", fg="white", width="500", font=("Helvetica","10","bold"))
XO_turn.place(relx=0.5, rely=0.05, anchor=CENTER)

result = Label(root, text="Match yet to begin", bg="grey", fg="white", width="500")
result.place(relx=0.5, rely=0.1, anchor=CENTER)

label_1 = Label(root, text="1", fg="royalblue", relief=FLAT, font=("Arial", "25"))
label_1.place(relx=0.25, rely=0.3, anchor=CENTER)

label_2 = Label(root, text="2", fg="royalblue", relief=FLAT, font=("Arial", "25"))
label_2.place(relx=0.55, rely=0.3, anchor=CENTER)

label_3 = Label(root, text="3", fg="royalblue", relief=FLAT, font=("Arial", "25"))
label_3.place(relx=0.75, rely=0.3, anchor=CENTER)

label_4 = Label(root, text="4", fg="royalblue", relief=FLAT, font=("Arial", "25"))
label_4.place(relx=0.25, rely=0.5, anchor=CENTER)

label_5 = Label(root, text="5", fg="royalblue", relief=FLAT, font=("Arial", "25"))
label_5.place(relx=0.55, rely=0.5, anchor=CENTER)

label_6 = Label(root, text="6", fg="royalblue", relief=FLAT, font=("Arial", "25"))
label_6.place(relx=0.75, rely=0.5, anchor=CENTER)

label_7 = Label(root, text="7", fg="royalblue", relief=FLAT, font=("Arial", "25"))
label_7.place(relx=0.25, rely=0.7, anchor=CENTER)

label_8 = Label(root, text="8", fg="royalblue", relief=FLAT, font=("Arial", "25"))
label_8.place(relx=0.55, rely=0.7, anchor=CENTER)

label_9 = Label(root, text="9", fg="royalblue", relief=FLAT, font=("Arial", "25"))
label_9.place(relx=0.75, rely=0.7, anchor=CENTER)

#Game Functions
value = "O"

def func1():
    btn_1.destroy()
    print("Function-1 in progress")
    global value
    if value == "O": 
        value = "X"
        XO_turn["text"] = "It is the turn of O"
    elif value == "X":
        value = "O"
        XO_turn["text"] = "It is the turn of X"
    label_1["text"] = value
    if label_1["text"] == "X" and label_2["text"] == "X" and label_3["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "X" and label_5["text"] == "X" and label_6["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "X" and label_8["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_4["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "X" and label_5["text"] == "X" and label_8["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_6["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_5["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_5["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_2["text"] == "O" and label_3["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "O" and label_5["text"] == "O" and label_6["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "O" and label_8["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_4["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "O" and label_5["text"] == "O" and label_8["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_6["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_5["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_5["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    else:
        result["text"] = "No victory as of yet!"
def func2():
    btn_2.destroy()
    print("Function-2 in progress")
    global value
    if value == "O": 
        value = "X"
        XO_turn["text"] = "It is the turn of O"
    elif value == "X":
        value = "O"
        XO_turn["text"] = "It is the turn of X"
    label_2["text"] = value
    if label_1["text"] == "X" and label_2["text"] == "X" and label_3["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "X" and label_5["text"] == "X" and label_6["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "X" and label_8["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_4["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "X" and label_5["text"] == "X" and label_8["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_6["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_5["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_5["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_2["text"] == "O" and label_3["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "O" and label_5["text"] == "O" and label_6["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "O" and label_8["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_4["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "O" and label_5["text"] == "O" and label_8["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_6["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_5["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_5["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    else:
        result["text"] = "No victory as of yet!"
def func3():
    btn_3.destroy()
    print("Function-3 in progress")
    global value
    if value == "O": 
        value = "X"
        XO_turn["text"] = "It is the turn of O"
    elif value == "X":
        value = "O"
        XO_turn["text"] = "It is the turn of X"
    label_3["text"] = value
    if label_1["text"] == "X" and label_2["text"] == "X" and label_3["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "X" and label_5["text"] == "X" and label_6["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "X" and label_8["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_4["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "X" and label_5["text"] == "X" and label_8["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_6["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_5["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_5["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_2["text"] == "O" and label_3["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "O" and label_5["text"] == "O" and label_6["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "O" and label_8["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_4["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "O" and label_5["text"] == "O" and label_8["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_6["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_5["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_5["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    else:
        result["text"] = "No victory as of yet!"
def func4():
    btn_4.destroy()
    print("Function-4 in progress")
    global value
    if value == "O": 
        value = "X"
        XO_turn["text"] = "It is the turn of O"
    elif value == "X":
        value = "O"
        XO_turn["text"] = "It is the turn of X"
    label_4["text"] = value
    if label_1["text"] == "X" and label_2["text"] == "X" and label_3["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "X" and label_5["text"] == "X" and label_6["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "X" and label_8["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_4["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "X" and label_5["text"] == "X" and label_8["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_6["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_5["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_5["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_2["text"] == "O" and label_3["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "O" and label_5["text"] == "O" and label_6["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "O" and label_8["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_4["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "O" and label_5["text"] == "O" and label_8["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_6["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_5["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_5["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    else:
        result["text"] = "No victory as of yet!"
def func5():
    btn_5.destroy()
    print("Function-5 in progress")
    global value
    if value == "O": 
        value = "X"
        XO_turn["text"] = "It is the turn of O"
    elif value == "X":
        value = "O"
        XO_turn["text"] = "It is the turn of X"
    label_5["text"] = value
    if label_1["text"] == "X" and label_2["text"] == "X" and label_3["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "X" and label_5["text"] == "X" and label_6["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "X" and label_8["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_4["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "X" and label_5["text"] == "X" and label_8["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_6["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_5["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_5["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_2["text"] == "O" and label_3["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "O" and label_5["text"] == "O" and label_6["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "O" and label_8["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_4["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "O" and label_5["text"] == "O" and label_8["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_6["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_5["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_5["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    else:
        result["text"] = "No victory as of yet!"
def func6():
    btn_6.destroy()
    print("Function-6 in progress")
    global value
    if value == "O": 
        value = "X"
        XO_turn["text"] = "It is the turn of O"
    elif value == "X":
        value = "O"
        XO_turn["text"] = "It is the turn of X"
    label_6["text"] = value
    if label_1["text"] == "X" and label_2["text"] == "X" and label_3["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "X" and label_5["text"] == "X" and label_6["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "X" and label_8["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_4["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "X" and label_5["text"] == "X" and label_8["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_6["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_5["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_5["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_2["text"] == "O" and label_3["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "O" and label_5["text"] == "O" and label_6["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "O" and label_8["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_4["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "O" and label_5["text"] == "O" and label_8["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_6["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_5["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_5["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    else:
        result["text"] = "No victory as of yet!"
def func7():
    btn_7.destroy()
    print("Function-7 in progress")
    global value
    if value == "O": 
        value = "X"
        XO_turn["text"] = "It is the turn of O"
    elif value == "X":
        value = "O"
        XO_turn["text"] = "It is the turn of X"
    label_7["text"] = value
    if label_1["text"] == "X" and label_2["text"] == "X" and label_3["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "X" and label_5["text"] == "X" and label_6["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "X" and label_8["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_4["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "X" and label_5["text"] == "X" and label_8["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_6["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_5["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_5["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_2["text"] == "O" and label_3["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "O" and label_5["text"] == "O" and label_6["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "O" and label_8["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_4["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "O" and label_5["text"] == "O" and label_8["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_6["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_5["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_5["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    else:
        result["text"] = "No victory as of yet!"
def func8():
    btn_8.destroy()
    print("Function-8 in progress")
    global value
    if value == "O": 
        value = "X"
        XO_turn["text"] = "It is the turn of O"
    elif value == "X":
        value = "O"
        XO_turn["text"] = "It is the turn of X"
    label_8["text"] = value
    if label_1["text"] == "X" and label_2["text"] == "X" and label_3["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "X" and label_5["text"] == "X" and label_6["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "X" and label_8["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_4["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "X" and label_5["text"] == "X" and label_8["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_6["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_5["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_5["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_2["text"] == "O" and label_3["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "O" and label_5["text"] == "O" and label_6["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "O" and label_8["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_4["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "O" and label_5["text"] == "O" and label_8["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_6["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_5["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_5["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    else:
        result["text"] = "No victory as of yet!"
def func9():
    btn_9.destroy()
    print("Function-9 in progress")
    global value
    if value == "O": 
        value = "X"
        XO_turn["text"] = "It is the turn of O"
    elif value == "X":
        value = "O"
        XO_turn["text"] = "It is the turn of X"
    label_9["text"] = value
    if label_1["text"] == "X" and label_2["text"] == "X" and label_3["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "X" and label_5["text"] == "X" and label_6["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "X" and label_8["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_4["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "X" and label_5["text"] == "X" and label_8["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_6["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "X" and label_5["text"] == "X" and label_9["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "X" and label_5["text"] == "X" and label_7["text"] == "X":
        result["text"] = "Hurray! X has won the match"
        synthesizer.say("X has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray X wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_2["text"] == "O" and label_3["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_4["text"] == "O" and label_5["text"] == "O" and label_6["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_7["text"] == "O" and label_8["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_4["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_2["text"] == "O" and label_5["text"] == "O" and label_8["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_6["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_1["text"] == "O" and label_5["text"] == "O" and label_9["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    elif label_3["text"] == "O" and label_5["text"] == "O" and label_7["text"] == "O":
        result["text"] = "Hurray! O has won the match"
        synthesizer.say("O has won the match!") 
        synthesizer.runAndWait() 
        synthesizer.stop()
        messagebox.showinfo("Match Finished", "Hurray O wins")
        btn_1.destroy()
        btn_2.destroy()
        btn_3.destroy()
        btn_4.destroy()
        btn_5.destroy()
        btn_6.destroy()
        btn_7.destroy()
        btn_8.destroy()
        btn_9.destroy()
    else:
        result["text"] = "No victory as of yet!"
def restart_func():
    print("Restart Function in progress")
    label_1["text"] = "1"
    label_2["text"] = "2"
    label_3["text"] = "3"
    label_4["text"] = "4"
    label_5["text"] = "5"
    label_6["text"] = "6"
    label_7["text"] = "7"
    label_8["text"] = "8"
    label_9["text"] = "9"
    btn_1 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func1)
    btn_1.place(relx=0.2, rely=0.3, anchor=CENTER)
    btn_2 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func2)
    btn_2.place(relx=0.5, rely=0.3, anchor=CENTER)
    btn_3 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func3)
    btn_3.place(relx=0.7, rely=0.3, anchor=CENTER)
    btn_4 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func4)
    btn_4.place(relx=0.2, rely=0.5, anchor=CENTER)
    btn_5 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func5)
    btn_5.place(relx=0.5, rely=0.5, anchor=CENTER)
    btn_6 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func6)
    btn_6.place(relx=0.7, rely=0.5, anchor=CENTER)
    btn_7 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func7)
    btn_7.place(relx=0.2, rely=0.7, anchor=CENTER)
    btn_8 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func8)
    btn_8.place(relx=0.5, rely=0.7, anchor=CENTER)
    btn_9 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func9)
    btn_9.place(relx=0.7, rely=0.7, anchor=CENTER)
    synthesizer.say("Another game starts!")
    synthesizer.runAndWait()
    synthesizer.stop()
    result["text"] = "Match yet to begin"

#GUI Buttons Loading
btn_1 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func1)
btn_1.place(relx=0.2, rely=0.3, anchor=CENTER)

btn_2 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func2)
btn_2.place(relx=0.5, rely=0.3, anchor=CENTER)

btn_3 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func3)
btn_3.place(relx=0.7, rely=0.3, anchor=CENTER)

btn_4 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func4)
btn_4.place(relx=0.2, rely=0.5, anchor=CENTER)

btn_5 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func5)
btn_5.place(relx=0.5, rely=0.5, anchor=CENTER)

btn_6 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func6)
btn_6.place(relx=0.7, rely=0.5, anchor=CENTER)

btn_7 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func7)
btn_7.place(relx=0.2, rely=0.7, anchor=CENTER)

btn_8 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func8)
btn_8.place(relx=0.5, rely=0.7, anchor=CENTER)

btn_9 = Button(root, fg="royalblue", relief=RAISED, font=("Arial", "25"), command=func9)
btn_9.place(relx=0.7, rely=0.7, anchor=CENTER)

restart_btn = Button(root, text="Restart Game", bg="green", fg="white", font=("Helvetica", "15"), command=restart_func)
restart_btn.place(relx=0.5, rely=0.9, anchor=CENTER)

#Ending the Program
root.mainloop()